spring:
  application:
    name: user-storage
  datasource:
    url: jdbc:mysql://database_host:database_port/database_name
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: database_username
    password: database_password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080