spring:
  application:
    name: user-storage
  datasource:
    url: jdbc:mysql://localhost:3306/user-storage
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: baxset8830
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080